# Generated by Django 5.2.8 on 2025-11-16 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_userrole_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='userrole',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roleinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('staff', 'staff'), ('admin', 'admin')], default='user', max_length=200),
        ),
    ]
